name: Build
on:
  push:
jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Install dependencies
        run: dotnet restore
      - name: Build project
        run: dotnet build -c Release --no-restore
      - name: Publish project
        run: dotnet publish ./src/Vulder.SchoolScrapper -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -o release
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Install dependencies
        run: dotnet restore
      - name: Build project
        run: dotnet build -c Release --no-restore
      - name: Publish project
        run: dotnet publish ./src/Vulder.SchoolScrapper -c Release -r osx.11.0-x64 --self-contained true -p:PublishSingleFile=true -o release
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Install dependencies
        run: dotnet restore
      - name: Build project
        run: dotnet build -c Release --no-restore
      - name: Publish project
        run: dotnet publish ./src/Vulder.SchoolScrapper -c Release -r linux-x64 --self-contained true -p:PublishSingleFile=true -o release
  deploy-artifact:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    needs: [windows, macos, ubuntu]
    runs-on: ${{ matrix.os }}
    steps:
      - id: commit
        uses: pr-mpt/actions-commit-hash@v1
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ runner.os }}-${{ steps.branch-name.outputs.current_branch }}-${{ steps.commit.outputs.short }}
          path: ./release